from __future__ import annotations

import os
import re
import signal
import subprocess
import threading
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Optional, Tuple

from database import get_all_settings, list_users

# 代理启停/安装互斥锁：后台重启和手动启停可能并发撞车
# （曾导致两个线程同时下载解压核心、互相删 zip 文件而 500）
_op_lock = threading.RLock()

PROXY_DIR = Path(os.getenv("MTP_PROXY_DIR", "/opt/mtproxy-panel/proxy"))
BIN_DIR = PROXY_DIR / "bin"
PID_DIR = PROXY_DIR / "pid"
PID_FILE = PID_DIR / "mtproxy.pid"
LOG_FILE = Path(os.getenv("MTP_PROXY_LOG", "/var/log/mtproxy-panel/proxy.log"))
PY_PROXY_URL = (
    "https://github.com/alexbers/mtprotoproxy/archive/refs/heads/master.zip"
)

# 公网 IP 缓存：{ip, ts(monotonic)}
_ip_cache: Dict[str, object] = {"ip": None, "ts": 0.0}
_IP_CACHE_TTL = 600.0

# 日志解析缓存：按文件 mtime+size 失效
_log_cache: Dict[str, object] = {"mtime": None, "size": None, "stats": {}}


def str_to_hex(text: str) -> str:
    return "".join(f"{ord(c):02x}" for c in text)


def build_client_secret(raw_secret: str, domain: str, mode: str = "ee") -> str:
    if mode == "off":
        return raw_secret
    if mode == "dd":
        return f"dd{raw_secret}"
    domain_hex = str_to_hex(domain)
    return f"ee{raw_secret}{domain_hex}"


def build_proxy_link(server: str, port: int, client_secret: str) -> Tuple[str, str]:
    # IPv6 必须加方括号，否则 tg:// 链接客户端解析不了
    host = f"[{server}]" if ":" in server else server
    http_link = f"https://t.me/proxy?server={host}&port={port}&secret={client_secret}"
    tg_link = f"tg://proxy?server={host}&port={port}&secret={client_secret}"
    return tg_link, http_link


def get_public_ip() -> str:
    """只返回 IPv4（IPv4 only：代理路由不走 IPv6）。

    严格校验：拿到的不是合法 IPv4 就丢弃换下一个源，都失败返回缓存或 127.0.0.1。
    """
    import ipaddress

    settings = get_all_settings()
    if settings.get("public_ip"):
        return settings["public_ip"]
    # 缓存 10 分钟：原来每次 API 请求都要 fork 一个 curl，现在最多 10 分钟一次
    now = time.monotonic()
    if _ip_cache["ip"] and now - _ip_cache["ts"] < _IP_CACHE_TTL:
        return _ip_cache["ip"]
    for url in ("https://api.ip.sb/ip", "https://ipv4.icanhazip.com"):
        try:
            result = subprocess.run(
                ["curl", "-fsSL", "--ipv4", "--connect-timeout", "5", url],
                capture_output=True,
                text=True,
                timeout=10,
                check=False,
            )
            ip = result.stdout.strip()
            ipaddress.IPv4Address(ip)  # 不是 IPv4 直接抛异常换下一个
            _ip_cache["ip"] = ip
            _ip_cache["ts"] = now
            return ip
        except Exception:
            continue
    return _ip_cache["ip"] or "127.0.0.1"


def _user_is_active(user: dict) -> bool:
    if not user["enabled"]:
        return False
    if user.get("expires_at"):
        try:
            exp = datetime.fromisoformat(user["expires_at"])
            if exp.tzinfo is None:
                exp = exp.replace(tzinfo=timezone.utc)
            if datetime.now(timezone.utc) >= exp:
                return False
        except ValueError:
            pass
    limit_gb = user["traffic_limit_gb"] or 0
    if limit_gb > 0:
        used = user["upload_bytes"] + user["download_bytes"]
        if used >= int(limit_gb * 1024 ** 3):
            return False
    return True


def _enabled_users_for_proxy() -> Dict[str, str]:
    users: Dict[str, str] = {}
    for user in list_users():
        if not _user_is_active(user):
            continue
        users[f"user{user['id']}"] = user["secret"]
    return users


def write_proxy_config() -> Path:
    settings = get_all_settings()
    users = _enabled_users_for_proxy()
    if not users:
        users = {"placeholder": "00000000000000000000000000000000"}

    tls_mode = settings.get("fake_tls_mode", "ee")
    if tls_mode == "off":
        modes = '"classic": True,\n    "secure": False,\n    "tls": False'
    else:
        modes = '"classic": False,\n    "secure": False,\n    "tls": True'

    config_path = BIN_DIR / "config.py"
    BIN_DIR.mkdir(parents=True, exist_ok=True)

    users_repr = ",\n    ".join(f'"{k}": "{v}"' for k, v in users.items())
    adtag = settings.get("adtag", "")
    # 有 adtag 才写这行：写 AD_TAG = None 会导致 mtprotoproxy 启动崩溃
    adtag_line = f'AD_TAG = "{adtag}"' if adtag else ""

    content = f"""# Auto-generated by MTProxy Panel
PORT = {int(settings.get("proxy_port", 443))}
USERS = {{
    {users_repr}
}}
MODES = {{
    {modes}
}}
TLS_DOMAIN = "{settings.get('domain', 'azure.microsoft.com')}"
{adtag_line}
STAT_PRINT_PERIOD = 30
"""
    config_path.write_text(content, encoding="utf-8")
    os.chmod(config_path, 0o600)  # 密钥文件仅属主可读写
    return config_path


def is_proxy_running() -> bool:
    if not PID_FILE.exists():
        return False
    try:
        pid = int(PID_FILE.read_text().strip())
    except ValueError:
        return False
    return Path(f"/proc/{pid}").exists()


def _find_proxy_script() -> Optional[Path]:
    for path in (BIN_DIR / "mtprotoproxy.py", Path("/home/mtproxy/bin/mtprotoproxy.py")):
        if path.exists():
            return path
    return None


def install_python_proxy() -> None:
    import shutil
    import zipfile

    # 双重检查锁：并发安装时只有一个线程真正下载解压
    if _find_proxy_script():
        return
    with _op_lock:
        if _find_proxy_script():
            return
        _do_install_proxy()


def _do_install_proxy() -> None:
    import shutil
    import zipfile

    BIN_DIR.mkdir(parents=True, exist_ok=True)

    zip_path = PROXY_DIR / "mtprotoproxy.zip"
    subprocess.run(["curl", "-fsSL", PY_PROXY_URL, "-o", str(zip_path)], check=True, timeout=120)
    with zipfile.ZipFile(zip_path) as zf:
        zf.extractall(PROXY_DIR / "extract")
    src = PROXY_DIR / "extract" / "mtprotoproxy-master"
    for name in ("mtprotoproxy.py", "pyaes"):
        src_item = src / name
        dst = BIN_DIR / name
        if src_item.is_dir():
            if dst.exists():
                shutil.rmtree(dst)
            shutil.copytree(src_item, dst)
        elif src_item.exists():
            shutil.copy2(src_item, dst)
    zip_path.unlink(missing_ok=True)
    shutil.rmtree(PROXY_DIR / "extract", ignore_errors=True)


def _pid_is_proxy(pid: int) -> bool:
    """确认该 PID 确实是我们的代理进程，防止 PID 复用误杀。"""
    try:
        cmd = Path(f"/proc/{pid}/cmdline").read_text()
        return "mtprotoproxy" in cmd
    except OSError:
        return False


def stop_proxy(timeout: float = 10.0) -> None:
    """停止代理（互斥：防止与并发的 start/restart 撞车）。"""
    with _op_lock:
        _do_stop(timeout)


def _do_stop(timeout: float = 10.0) -> None:
    if not PID_FILE.exists():
        return
    try:
        pid = int(PID_FILE.read_text().strip())
    except ValueError:
        PID_FILE.unlink(missing_ok=True)
        return
    if not _pid_is_proxy(pid):
        # PID 文件过期且 PID 已被其他进程复用，直接清理
        PID_FILE.unlink(missing_ok=True)
        return
    try:
        os.kill(pid, signal.SIGTERM)
    except (ProcessLookupError, PermissionError):
        pass
    # 等待进程真正退出：3 秒后升级为 SIGKILL，最多等 timeout 秒
    # 原来只 sleep 1 秒就起新进程，旧进程可能还在，导致双进程抢端口
    deadline = time.monotonic() + timeout
    killed = False
    while time.monotonic() < deadline:
        if not Path(f"/proc/{pid}").exists() or not _pid_is_proxy(pid):
            break
        if not killed and time.monotonic() > deadline - timeout + 3:
            try:
                os.kill(pid, signal.SIGKILL)
            except (ProcessLookupError, PermissionError):
                break
            killed = True
        time.sleep(0.2)
    PID_FILE.unlink(missing_ok=True)


def start_proxy() -> bool:
    """启动代理（互斥：防止与并发的 stop/restart 撞车）。"""
    with _op_lock:
        return _do_start()


def _do_start() -> bool:
    install_python_proxy()
    script = _find_proxy_script()
    if not script:
        return False

    write_proxy_config()
    _do_stop()

    PID_DIR.mkdir(parents=True, exist_ok=True)
    LOG_FILE.parent.mkdir(parents=True, exist_ok=True)

    log_fp = open(LOG_FILE, "a", encoding="utf-8")
    proc = subprocess.Popen(
        ["python3", str(script), str(BIN_DIR / "config.py")],
        stdout=log_fp,
        stderr=subprocess.STDOUT,
        cwd=str(BIN_DIR),
        start_new_session=True,
    )
    log_fp.close()  # 子进程已 dup 该 fd，父进程关闭避免 fd 泄漏
    PID_FILE.write_text(str(proc.pid))
    time.sleep(2)
    if proc.poll() is not None:
        PID_FILE.unlink(missing_ok=True)
        return False
    return is_proxy_running()


def restart_proxy() -> bool:
    with _op_lock:
        _do_stop()
        return _do_start()


def parse_stats_from_log() -> Dict[str, Dict[str, int]]:
    if not LOG_FILE.exists():
        return {}
    try:
        st = LOG_FILE.stat()
    except OSError:
        return {}
    # 文件没变直接返回缓存：原来每次 dashboard/用户列表都要扫 300KB 日志
    if _log_cache["mtime"] == st.st_mtime_ns and _log_cache["size"] == st.st_size:
        return _log_cache["stats"]  # type: ignore[return-value]

    text = LOG_FILE.read_text(encoding="utf-8", errors="ignore")[-300000:]
    patterns = [
        re.compile(
            r"(?P<user>user\d+|\w+):\s+(?P<connects>\d+)\s+connects,\s+"
            r"(?P<read>\d+)\s+bytes read,\s+(?P<written>\d+)\s+bytes written"
        ),
        re.compile(
            r"Stats for (?P<user>user\d+|\w+):\s+"
            r"(?P<connects>\d+)\s+connects,\s+"
            r"(?P<read>\d+)\s+bytes read,\s+(?P<written>\d+)\s+bytes written"
        ),
    ]
    stats: Dict[str, Dict[str, int]] = {}
    for pattern in patterns:
        for match in pattern.finditer(text):
            stats[match.group("user")] = {
                "connects": int(match.group("connects")),
                "download": int(match.group("read")),
                "upload": int(match.group("written")),
            }
    _log_cache.update({"mtime": st.st_mtime_ns, "size": st.st_size, "stats": stats})
    return stats


def count_connections(port: int) -> int:
    try:
        result = subprocess.run(
            ["ss", "-H", "-tn", f"sport = :{port}"],
            capture_output=True,
            text=True,
            timeout=5,
            check=False,
        )
        return len([l for l in result.stdout.splitlines() if "ESTAB" in l])
    except Exception:
        return 0


def validate_domain(domain: str) -> bool:
    try:
        result = subprocess.run(
            ["curl", "-I", "-m", "8", "-o", "/dev/null", "-s", "-w", "%{http_code}", f"https://{domain}"],
            capture_output=True,
            text=True,
            timeout=12,
            check=False,
        )
        code = result.stdout.strip()
        return code in ("200", "301", "302", "403")
    except Exception:
        return False
