from __future__ import annotations

import os
import re
import signal
import subprocess
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Optional, Tuple

from database import get_all_settings, list_users

PROXY_DIR = Path(os.getenv("MTP_PROXY_DIR", "/opt/mtproxy-panel/proxy"))
BIN_DIR = PROXY_DIR / "bin"
PID_DIR = PROXY_DIR / "pid"
PID_FILE = PID_DIR / "mtproxy.pid"
LOG_FILE = Path(os.getenv("MTP_PROXY_LOG", "/var/log/mtproxy-panel/proxy.log"))
PY_PROXY_URL = (
    "https://github.com/alexbers/mtprotoproxy/archive/refs/heads/master.zip"
)


def str_to_hex(text: str) -> str:
    return "".join(f"{ord(c):02x}" for c in text)


def build_client_secret(raw_secret: str, domain: str, mode: str = "ee") -> str:
    if mode == "off":
        return raw_secret
    if mode == "dd":
        return f"dd{raw_secret}"
    domain_hex = str_to_hex(domain)
    return f"ee{raw_secret}{domain_hex}"


def build_proxy_link(server: str, port: int, client_secret: str) -> Tuple[str, str]:
    http_link = f"https://t.me/proxy?server={server}&port={port}&secret={client_secret}"
    tg_link = f"tg://proxy?server={server}&port={port}&secret={client_secret}"
    return tg_link, http_link


def get_public_ip() -> str:
    settings = get_all_settings()
    if settings.get("public_ip"):
        return settings["public_ip"]
    try:
        result = subprocess.run(
            ["curl", "-fsSL", "--ipv4", "--connect-timeout", "5", "https://api.ip.sb/ip"],
            capture_output=True,
            text=True,
            timeout=10,
            check=False,
        )
        if result.stdout.strip():
            return result.stdout.strip()
    except Exception:
        pass
    return "127.0.0.1"


def _user_is_active(user: dict) -> bool:
    if not user["enabled"]:
        return False
    if user.get("expires_at"):
        try:
            exp = datetime.fromisoformat(user["expires_at"])
            if exp.tzinfo is None:
                exp = exp.replace(tzinfo=timezone.utc)
            if datetime.now(timezone.utc) >= exp:
                return False
        except ValueError:
            pass
    limit_gb = user["traffic_limit_gb"] or 0
    if limit_gb > 0:
        used = user["upload_bytes"] + user["download_bytes"]
        if used >= int(limit_gb * 1024 ** 3):
            return False
    return True


def _enabled_users_for_proxy() -> Dict[str, str]:
    users: Dict[str, str] = {}
    for user in list_users():
        if not _user_is_active(user):
            continue
        users[f"user{user['id']}"] = user["secret"]
    return users


def write_proxy_config() -> Path:
    settings = get_all_settings()
    users = _enabled_users_for_proxy()
    if not users:
        users = {"placeholder": "00000000000000000000000000000000"}

    tls_mode = settings.get("fake_tls_mode", "ee")
    if tls_mode == "off":
        modes = '"classic": True,\n    "secure": False,\n    "tls": False'
    else:
        modes = '"classic": False,\n    "secure": False,\n    "tls": True'

    config_path = BIN_DIR / "config.py"
    BIN_DIR.mkdir(parents=True, exist_ok=True)

    users_repr = ",\n    ".join(f'"{k}": "{v}"' for k, v in users.items())
    adtag = settings.get("adtag", "")
    adtag_line = f'AD_TAG = "{adtag}"' if adtag else "AD_TAG = None"

    content = f"""# Auto-generated by MTProxy Panel
PORT = {int(settings.get("proxy_port", 443))}
USERS = {{
    {users_repr}
}}
MODES = {{
    {modes}
}}
TLS_DOMAIN = "{settings.get('domain', 'azure.microsoft.com')}"
{adtag_line}
STAT_PRINT_PERIOD = 30
"""
    config_path.write_text(content, encoding="utf-8")
    return config_path


def is_proxy_running() -> bool:
    if not PID_FILE.exists():
        return False
    try:
        pid = int(PID_FILE.read_text().strip())
    except ValueError:
        return False
    return Path(f"/proc/{pid}").exists()


def _find_proxy_script() -> Optional[Path]:
    for path in (BIN_DIR / "mtprotoproxy.py", Path("/home/mtproxy/bin/mtprotoproxy.py")):
        if path.exists():
            return path
    return None


def install_python_proxy() -> None:
    import shutil
    import zipfile

    BIN_DIR.mkdir(parents=True, exist_ok=True)
    if _find_proxy_script():
        return

    zip_path = PROXY_DIR / "mtprotoproxy.zip"
    subprocess.run(["curl", "-fsSL", PY_PROXY_URL, "-o", str(zip_path)], check=True, timeout=120)
    with zipfile.ZipFile(zip_path) as zf:
        zf.extractall(PROXY_DIR / "extract")
    src = PROXY_DIR / "extract" / "mtprotoproxy-master"
    for name in ("mtprotoproxy.py", "pyaes"):
        src_item = src / name
        dst = BIN_DIR / name
        if src_item.is_dir():
            if dst.exists():
                shutil.rmtree(dst)
            shutil.copytree(src_item, dst)
        elif src_item.exists():
            shutil.copy2(src_item, dst)
    zip_path.unlink(missing_ok=True)
    shutil.rmtree(PROXY_DIR / "extract", ignore_errors=True)


def stop_proxy() -> None:
    if not PID_FILE.exists():
        return
    try:
        pid = int(PID_FILE.read_text().strip())
        os.kill(pid, signal.SIGTERM)
        time.sleep(1)
        if Path(f"/proc/{pid}").exists():
            os.kill(pid, signal.SIGKILL)
    except (ProcessLookupError, ValueError, PermissionError):
        pass
    PID_FILE.unlink(missing_ok=True)


def start_proxy() -> bool:
    install_python_proxy()
    script = _find_proxy_script()
    if not script:
        return False

    write_proxy_config()
    stop_proxy()

    PID_DIR.mkdir(parents=True, exist_ok=True)
    LOG_FILE.parent.mkdir(parents=True, exist_ok=True)

    log_fp = open(LOG_FILE, "a", encoding="utf-8")
    proc = subprocess.Popen(
        ["python3", str(script), str(BIN_DIR / "config.py")],
        stdout=log_fp,
        stderr=subprocess.STDOUT,
        cwd=str(BIN_DIR),
        start_new_session=True,
    )
    PID_FILE.write_text(str(proc.pid))
    time.sleep(2)
    if proc.poll() is not None:
        PID_FILE.unlink(missing_ok=True)
        return False
    return is_proxy_running()


def restart_proxy() -> bool:
    stop_proxy()
    return start_proxy()


def parse_stats_from_log() -> Dict[str, Dict[str, int]]:
    if not LOG_FILE.exists():
        return {}

    text = LOG_FILE.read_text(encoding="utf-8", errors="ignore")[-300000:]
    patterns = [
        re.compile(
            r"(?P<user>user\d+|\w+):\s+(?P<connects>\d+)\s+connects,\s+"
            r"(?P<read>\d+)\s+bytes read,\s+(?P<written>\d+)\s+bytes written"
        ),
        re.compile(
            r"Stats for (?P<user>user\d+|\w+):\s+"
            r"(?P<connects>\d+)\s+connects,\s+"
            r"(?P<read>\d+)\s+bytes read,\s+(?P<written>\d+)\s+bytes written"
        ),
    ]
    stats: Dict[str, Dict[str, int]] = {}
    for pattern in patterns:
        for match in pattern.finditer(text):
            stats[match.group("user")] = {
                "connects": int(match.group("connects")),
                "download": int(match.group("read")),
                "upload": int(match.group("written")),
            }
    return stats


def count_connections(port: int) -> int:
    try:
        result = subprocess.run(
            ["ss", "-H", "-tn", f"sport = :{port}"],
            capture_output=True,
            text=True,
            timeout=5,
            check=False,
        )
        return len([l for l in result.stdout.splitlines() if "ESTAB" in l])
    except Exception:
        return 0


def validate_domain(domain: str) -> bool:
    try:
        result = subprocess.run(
            ["curl", "-I", "-m", "8", "-o", "/dev/null", "-s", "-w", "%{http_code}", f"https://{domain}"],
            capture_output=True,
            text=True,
            timeout=12,
            check=False,
        )
        code = result.stdout.strip()
        return code in ("200", "301", "302", "403")
    except Exception:
        return False