#!/usr/bin/env python3
"""MTProxy 节点 agent：运行在被管服务器上，供主面板调用。

接口（均需 Authorization: Bearer <API_TOKEN>，/health 除外）：
  GET  /health      存活检查
  GET  /stats       系统状态 + 代理状态 + 用户数
  POST /sync-users  同步用户列表 {users: [{secret, enabled}]}
"""
from __future__ import annotations

import json
import os
import secrets
import sys
from pathlib import Path
from typing import Any, Dict, List

from fastapi import Depends, FastAPI, HTTPException, status
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer
from pydantic import BaseModel

# 复用主面板的代理管理逻辑
sys.path.insert(0, str(Path(__file__).parent))
from mtproxy_service import (
    is_proxy_running,
    restart_proxy,
    start_proxy,
)
from system_monitor import get_system_status

DATA_DIR = Path(os.getenv("MTP_NODE_DATA", "/opt/mtproxy-node/data"))
USERS_FILE = DATA_DIR / "users.json"
CONFIG_FILE = DATA_DIR / "node.json"
API_TOKEN_FILE = DATA_DIR / "api_token"

app = FastAPI(title="MTProxy Node Agent")
_bearer = HTTPBearer(auto_error=False)


def _load_config() -> Dict[str, Any]:
    if CONFIG_FILE.exists():
        return json.loads(CONFIG_FILE.read_text())
    return {"proxy_port": 443, "domain": "azure.microsoft.com",
            "fake_tls_mode": "ee", "adtag": ""}


def _load_users() -> List[Dict[str, Any]]:
    if USERS_FILE.exists():
        return json.loads(USERS_FILE.read_text())
    return []


def _get_token() -> str:
    return API_TOKEN_FILE.read_text().strip() if API_TOKEN_FILE.exists() else ""


def verify_node_token(
    cred: HTTPAuthorizationCredentials = Depends(_bearer),
) -> str:
    expected = _get_token()
    if not expected or not cred or not secrets.compare_digest(cred.credentials, expected):
        raise HTTPException(status.HTTP_401_UNAUTHORIZED, "Token 无效")
    return cred.credentials


class SyncUsersRequest(BaseModel):
    users: List[Dict[str, Any]]


class NodeConfigRequest(BaseModel):
    proxy_port: int | None = None
    domain: str | None = None
    fake_tls_mode: str | None = None


def _write_proxy_config(users: List[Dict[str, Any]], cfg: Dict[str, Any]) -> Path:
    """根据同步的用户列表写 mtprotoproxy 配置。"""
    from mtproxy_service import BIN_DIR
    enabled = {f"user{i}": u["secret"] for i, u in enumerate(users) if u.get("enabled")}
    if not enabled:
        enabled = {"placeholder": "00000000000000000000000000000000"}

    tls_mode = cfg.get("fake_tls_mode", "ee")
    if tls_mode == "off":
        modes = '"classic": True,\n    "secure": False,\n    "tls": False'
    else:
        modes = '"classic": False,\n    "secure": False,\n    "tls": True'

    users_repr = ",\n    ".join(f'"{k}": "{v}"' for k, v in enabled.items())
    adtag = cfg.get("adtag", "")
    adtag_line = f'AD_TAG = "{adtag}"' if adtag else ""

    content = f"""# Auto-generated by MTProxy Node Agent
PORT = {int(cfg.get("proxy_port", 443))}
USERS = {{
    {users_repr}
}}
MODES = {{
    {modes}
}}
TLS_DOMAIN = "{cfg.get('domain', 'azure.microsoft.com')}"
{adtag_line}
STAT_PRINT_PERIOD = 30
"""
    BIN_DIR.mkdir(parents=True, exist_ok=True)
    config_path = BIN_DIR / "config.py"
    config_path.write_text(content, encoding="utf-8")
    os.chmod(config_path, 0o600)
    return config_path


@app.get("/health")
def health() -> Dict[str, str]:
    return {"status": "ok"}


@app.get("/stats")
def stats(_: str = Depends(verify_node_token)) -> Dict[str, Any]:
    sys_status = get_system_status()
    return {
        "cpu_percent": sys_status.get("cpu_percent", 0),
        "mem_percent": sys_status.get("mem_percent", 0),
        "proxy_running": is_proxy_running(),
        "user_count": len([u for u in _load_users() if u.get("enabled")]),
    }


@app.post("/sync-users")
def sync_users(body: SyncUsersRequest, _: str = Depends(verify_node_token)) -> Dict[str, str]:
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    USERS_FILE.write_text(json.dumps(body.users, ensure_ascii=False))
    os.chmod(USERS_FILE, 0o600)
    cfg = _load_config()
    _write_proxy_config(body.users, cfg)
    restart_proxy()
    return {"status": "ok", "count": len(body.users)}


@app.post("/proxy/start")
def proxy_start(_: str = Depends(verify_node_token)) -> Dict[str, Any]:
    return {"running": start_proxy()}


@app.post("/config")
def update_config(body: NodeConfigRequest, _: str = Depends(verify_node_token)) -> Dict[str, str]:
    """更新节点配置（代理端口/伪装域名），自动重启代理生效。"""
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    cfg = _load_config()
    if body.proxy_port is not None:
        cfg["proxy_port"] = body.proxy_port
    if body.domain is not None:
        cfg["domain"] = body.domain
    if body.fake_tls_mode is not None:
        cfg["fake_tls_mode"] = body.fake_tls_mode
    CONFIG_FILE.write_text(json.dumps(cfg, ensure_ascii=False))
    _write_proxy_config(_load_users(), cfg)
    restart_proxy()
    return {"status": "ok"}


if __name__ == "__main__":
    import uvicorn
    port = int(os.getenv("MTP_NODE_PORT", "8899"))
    uvicorn.run(app, host="0.0.0.0", port=port)
